### PR TITLE
Correct start version for cancer ini file, starting from 0.1

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR adds | fixes:

Version of cancer rank scoring ini file starting from 0.1

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by dnil** [comment]
Ok I guess but you will now have to remember to skip or edit the 1.0-1.1 that were loaded before. Not sure if they are just fake - or due to the fact that we did have one since your first month or so, remember? Anyway, those cases are not many so if this change solves something else that is fine.

**Comment by hassanfa** [comment]
> Ok I guess but you will now have to remember to skip or edit the 1.0-1.1 that were loaded before. Not sure if they are just fake - or due to the fact that we did have one since your first month or so, remember? Anyway, those cases are not many so if this change solves something else that is fine.

I see. Where do we have that version? Since this is not a definitive draft, I thought we shouldn't start from 1. Reason: I also added it to BALSAMIC as a downloadable reference.

**Comment by dnil** [comment]
You tell me - I think it was on your editor.. 😉 Anyway, few cases, same thing, different names - no matter. As you prefer!

**Comment by hassanfa** [comment]
I also remember we talked about version at some point, and when I was downloading it, I noticed it is version 1.2 in the master branch. If you don't mind, lets start from 0.1. This way it'll feel great to bump it to 1.0 😌

**Pull request merged**
