### PR TITLE
Feature/mip10 update

### PR DESCRIPTION
**Pull request by jemten**
### This PR adds | fixes:
- Updates for MIP 10

**How to prepare for test**:
- [ ] `ssh` to ...
- [ ] Install on stage:
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`

### How to test:
-

### Expected outcome:
- [ ]

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henrikstranneheim — APPROVED** [review]
Guess it is only loqus that changed?

**Comment by henrikstranneheim** [comment]
For the rank model I mean

**Comment by jemten** [comment]
> Guess it is only loqus that changed?

Yes. I used the same cut offs that we use for gnomad AF. Seemed to correspond roughly to the observation frequencies in earlier loqus exports. Do you think it should be more strict/lenient?

**Comment by henrikstranneheim** [comment]
Let's roll with this and see how it fares in the validation using Mutacc. I think it should be enough cases in there to be adequate cut-offs.

**Pull request merged**
