### PR TITLE
feat(rank_models): Added older rank models

### PR DESCRIPTION
**Pull request by henrikstranneheim**

### CODE REVIEW

**Comment by henrikstranneheim** [comment]
@jemten Bump

**Comment by dnil** [comment]
Still missing that 1.1, but otw fine!

**Comment by henrikstranneheim** [comment]
Yes, I have asked Hassan to look into it see https://github.com/Clinical-Genomics/reference-files/issues/11

**Comment by henrikstranneheim** [comment]
Let's keep the issue open until its it's is added in another PR

**Pull request merged**
